// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: widget.proto

package widget_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WidgetService_GetWidget_FullMethodName = "/widget_proto.WidgetService/GetWidget"
)

// WidgetServiceClient is the client API for WidgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WidgetServiceClient interface {
	GetWidget(ctx context.Context, in *WidgetRequest, opts ...grpc.CallOption) (*WidgetResponse, error)
}

type widgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetServiceClient(cc grpc.ClientConnInterface) WidgetServiceClient {
	return &widgetServiceClient{cc}
}

func (c *widgetServiceClient) GetWidget(ctx context.Context, in *WidgetRequest, opts ...grpc.CallOption) (*WidgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetResponse)
	err := c.cc.Invoke(ctx, WidgetService_GetWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetServiceServer is the server API for WidgetService service.
// All implementations must embed UnimplementedWidgetServiceServer
// for forward compatibility.
type WidgetServiceServer interface {
	GetWidget(context.Context, *WidgetRequest) (*WidgetResponse, error)
	mustEmbedUnimplementedWidgetServiceServer()
}

// UnimplementedWidgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWidgetServiceServer struct{}

func (UnimplementedWidgetServiceServer) GetWidget(context.Context, *WidgetRequest) (*WidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWidget not implemented")
}
func (UnimplementedWidgetServiceServer) mustEmbedUnimplementedWidgetServiceServer() {}
func (UnimplementedWidgetServiceServer) testEmbeddedByValue()                       {}

// UnsafeWidgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WidgetServiceServer will
// result in compilation errors.
type UnsafeWidgetServiceServer interface {
	mustEmbedUnimplementedWidgetServiceServer()
}

func RegisterWidgetServiceServer(s grpc.ServiceRegistrar, srv WidgetServiceServer) {
	// If the following call pancis, it indicates UnimplementedWidgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WidgetService_ServiceDesc, srv)
}

func _WidgetService_GetWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetService_GetWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetWidget(ctx, req.(*WidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WidgetService_ServiceDesc is the grpc.ServiceDesc for WidgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WidgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "widget_proto.WidgetService",
	HandlerType: (*WidgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWidget",
			Handler:    _WidgetService_GetWidget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "widget.proto",
}
