// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: widget.proto

package widget_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetRequest) Reset() {
	*x = WidgetRequest{}
	mi := &file_widget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetRequest) ProtoMessage() {}

func (x *WidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetRequest.ProtoReflect.Descriptor instead.
func (*WidgetRequest) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stats         string                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetResponse) Reset() {
	*x = WidgetResponse{}
	mi := &file_widget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetResponse) ProtoMessage() {}

func (x *WidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetResponse.ProtoReflect.Descriptor instead.
func (*WidgetResponse) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{1}
}

func (x *WidgetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WidgetResponse) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

var File_widget_proto protoreflect.FileDescriptor

const file_widget_proto_rawDesc = "" +
	"\n" +
	"\fwidget.proto\x12\fwidget_proto\"#\n" +
	"\rWidgetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x0eWidgetResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05stats\x18\x02 \x01(\tR\x05stats2W\n" +
	"\rWidgetService\x12F\n" +
	"\tGetWidget\x12\x1b.widget_proto.WidgetRequest\x1a\x1c.widget_proto.WidgetResponseBAZ?github.com/sisyphoscar/product-battle/proto/widget;widget_protob\x06proto3"

var (
	file_widget_proto_rawDescOnce sync.Once
	file_widget_proto_rawDescData []byte
)

func file_widget_proto_rawDescGZIP() []byte {
	file_widget_proto_rawDescOnce.Do(func() {
		file_widget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_widget_proto_rawDesc), len(file_widget_proto_rawDesc)))
	})
	return file_widget_proto_rawDescData
}

var file_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_widget_proto_goTypes = []any{
	(*WidgetRequest)(nil),  // 0: widget_proto.WidgetRequest
	(*WidgetResponse)(nil), // 1: widget_proto.WidgetResponse
}
var file_widget_proto_depIdxs = []int32{
	0, // 0: widget_proto.WidgetService.GetWidget:input_type -> widget_proto.WidgetRequest
	1, // 1: widget_proto.WidgetService.GetWidget:output_type -> widget_proto.WidgetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_widget_proto_init() }
func file_widget_proto_init() {
	if File_widget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_widget_proto_rawDesc), len(file_widget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_widget_proto_goTypes,
		DependencyIndexes: file_widget_proto_depIdxs,
		MessageInfos:      file_widget_proto_msgTypes,
	}.Build()
	File_widget_proto = out.File
	file_widget_proto_goTypes = nil
	file_widget_proto_depIdxs = nil
}
